name: Build ApexFlow for Windows

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Create virtual environment
      run: |
        python -m venv .venv
        
    - name: Install dependencies
      run: |
        .venv\Scripts\python -m pip install --upgrade pip
        .venv\Scripts\pip install -r requirements.txt
        
    - name: Build with pyside6-deploy
      run: |
        .venv\Scripts\activate
        pyinstaller --noconfirm --onefile --windowed --icon "ui\apexFlowIcon.ico" --name "apexflow" --clean --manifest "manifest.xml" --add-data "ui;ui" --add-data "ai.py;." --add-data "config.py;." --add-data "data.py;." --collect-all "nsepython" --hidden-import "scipy.special._cdflib"  --hidden-import "scipy.stats.distributions" --hidden-import "scipy.stats._distn_infrastructure" "D:\Dev\ApexFlow\app.pyw"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ApexFlow-Windows
        path: dist/apexflow.exe
